version: '3.8'

services:
  psql:
    container_name: psql
    image: postgres:15-alpine
    volumes:
      - ./db/data:/pgdata
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/pgdata
    ports:
      - '5432:5432'
    restart: always
