version: '3.8'

services:
  psql:
    container_name: psql
    image: postgres:15-alpine
    volumes:
      - ./db/data:/pgdata
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/pgdata
    ports:
      - '5432:5432'
    restart: always

  mongo:
    container_name: mongo
    image: mongo:7.0-rc-jammy
    volumes:
      - ./db/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    restart: always

  app_dev:
    container_name: app_dev
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './src/:/usr/app/src/'
      - './assets/:/usr/app/assets/'
      - './prisma/:/usr/app/prisma/'
    command: bash -c "npm run dev"
    ports:
      - '3333:3333'
    depends_on:
      - psql
      - mongo
    links:
      - psql
      - mongo
    environment:
      - NODE_ENV=development
