import { ListBeerRepository } from '../../../domain/repository/beer'

export const beers: ListBeerRepository.Result['beers'] = [
	{
		id: 1,
		name: 'Buzz',
		description:
			'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 4.5,
		ibu: 60,
		ebc: 20,
		category: 'Pale Ale',
		foodPairing: [
			'Spicy chicken tikka masala',
			'Grilled chicken quesadilla',
			'Caramel toffee cake',
		],
		brewersTips:
			'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 2,
		name: 'Trashy Blonde',
		description:
			'You know how it is, sometimes you just fancy something a little different. For those times we created the Trashy Blonde. A juxtaposition of styles, continental pilsner with New World hops. ',
		imageUrl: 'https://images.punkapi.com/v2/2.png',
		abv: 4.1,
		ibu: 41.5,
		ebc: 15,
		category: 'Blonde',
		foodPairing: [
			'Fresh crab with lemon',
			'Garlic butter dipping sauce',
			'Goats cheese salad',
			'Creamy lemon bar doused in powdered sugar',
		],
		brewersTips:
			"If you're after a crisp, clean and crushable beer, you've come to the right place.",
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 3,
		name: 'Berliner Weisse With Yuzu - B-Sides',
		description: 'Japanese citrus fruit intensifies the sour nature of this German classic.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 4.2,
		ibu: 8,
		ebc: 8,
		category: 'Berliner Weisse',
		foodPairing: ['Smoked chicken wings', 'Miso ramen', 'Yuzu cheesecake'],
		brewersTips:
			'Fermenting with a lager yeast at ale temperatures gives the crispness of a lager and the fruitiness of an ale.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 4,
		name: 'Pilsen Lager',
		description: 'Our indulgent Pilsner is brewed with copious amounts of 100% Saaz hops',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 6.3,
		ibu: 55,
		ebc: 10,
		category: 'Pilsen',
		foodPairing: [
			'Spicy crab cakes',
			'Spicy cucumber and carrot Thai salad',
			'Spicy chocolate covered almonds',
		],
		brewersTips:
			'After primary fermentation is complete, we drop the temperature and condition the beer at 0°C for 4 weeks. This greatly improves the clarity of the beer, and leaves us with a crisp, fresh lager.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 5,
		name: 'Avery Brown Dredge',
		description:
			'A titanic malt bill props up a high ABV, while a hefty dose of hops charge the palate with notes of bitter citrus.',
		imageUrl: 'https://images.punkapi.com/v2/5.png',
		abv: 7.2,
		ibu: 70,
		ebc: 30,
		category: 'Brown Ale',
		foodPairing: ['Venison with celeriac mash', 'Gouda cheese', 'Chocolate and raspberry torte'],
		brewersTips:
			'Boil down to desired OG (about 17 litres). Use the German ale yeast for a cleaner finish.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 6,
		name: 'Electric India',
		description: 'A saison style beer brewed with fresh elderflowers and lemon zest.',
		imageUrl: 'https://images.punkapi.com/v2/6.png',
		abv: 5.2,
		ibu: 38,
		ebc: 15,
		category: 'Saison',
		foodPairing: [
			'Spicy chicken skewers',
			'Fish tacos with hot sauce',
			'Lemon pound cake with a ice sugar glaze',
		],
		brewersTips: 'Be careful when grating in the lemon zest - leave the pith behind.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},

	{
		id: 7,
		name: 'AB:12',
		description:
			'This Abstrakt started life as a simple imperial Ale, but upon the addition of fresh Scottish raspberries and strawberries, and left to mature for 2 years in Invergordon whisky casks that had held whisky for over 40 years, this beer transcended into something new.',
		imageUrl: 'https://images.punkapi.com/v2/7.png',
		abv: 11.2,
		ibu: 35,
		ebc: 80,
		category: 'Strong Ale',
		foodPairing: [
			'Dark chocolate dipped strawberries',
			'Cheesecake with raspberry coulis',
			'Roast venison with a dark berry jus',
		],
		brewersTips:
			'Make sure you have plenty of fresh Scottish raspberries and strawberries to hand when you are brewing this beer.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 8,
		name: 'Fake Lager',
		description:
			'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 4.5,
		ibu: 60,
		ebc: 20,
		category: 'Pale Ale',
		foodPairing: [
			'Spicy chicken tikka masala',
			'Grilled chicken quesadilla',
			'Caramel toffee cake',
		],
		brewersTips:
			'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 9,
		name: 'AB:07',
		description: 'A rich and decadent imperial stout layered with copious amounts of dark fruit. ',
		imageUrl: 'https://images.punkapi.com/v2/9.png',
		abv: 12.5,
		ibu: 75,
		ebc: 180,
		category: 'Imperial Stout',
		foodPairing: [
			'Stilton on gingerbread biscuits',
			'Pot roasted artichokes',
			'Lamb chops with caramelised figs',
		],
		brewersTips: 'Leave this beer to mellow in the cellar for a few months before cracking open.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},

	{
		id: 10,
		name: 'Bramling X',
		description: 'A dark and brooding stout with an intense, dry, dark chocolate flavour.',
		imageUrl: 'https://images.punkapi.com/v2/10.png',
		abv: 7.5,
		ibu: 60,
		ebc: 180,
		category: 'Stout',
		foodPairing: [
			'Stilton on gingerbread biscuits',
			'Pot roasted artichokes',
			'Lamb chops with caramelised figs',
		],
		brewersTips: 'Leave this beer to mellow in the cellar for a few months before cracking open.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 11,
		name: 'Misspent Youth',
		description:
			'The brainchild of our small batch brewer, George Woods. A dangerously drinkable milk sugar- infused IPA.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 7.3,
		ibu: 70,
		ebc: 15,
		category: 'IPA',
		foodPairing: [
			'Spicy wings with blue cheese dip',
			'Pan seared scallops with a chilli sauce',
			'Cheesecake with raspberry coulis',
		],
		brewersTips: 'If you can’t get hold of any Bramling Cross try using Citra instead.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 12,
		name: 'Arcade Nation',
		description:
			'A juxtaposition of styles, this black lager takes the light, hoppy notes of a Pilsner and combines them with the roasted malts and rich flavours of a stout.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 5.3,
		ibu: 35,
		ebc: 40,
		category: 'Black IPA',
		foodPairing: [
			'King prawn kebabs',
			'Halibut with a mango and tomato salad',
			'Milk chocolate truffles',
		],
		brewersTips:
			'Be as accurate as possible when weighing out your malts to ensure you strike the right balance.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},

	{
		id: 13,
		name: 'Movember',
		description:
			'A deliciously robust, black malted beer with a decadent dark, dry cocoa flavour that provides an enticing backdrop to the Cascade hops.',
		imageUrl: 'https://images.punkapi.com/v2/keg.png',
		abv: 4.5,
		ibu: 50,
		ebc: 80,
		category: 'Stout',
		foodPairing: ['Vegetable egg scramble', 'Margherita pizza', 'Fresh berry crisp tart'],
		brewersTips:
			'If you’re struggling with the chocolate notes in the beer, try it with a few squares of dark chocolate.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 14,
		name: 'Alpha Dog',
		description:
			'A beer with bark and bite, this IPA is aggressively hopped with a nice malty backbone.',
		imageUrl: 'https://images.punkapi.com/v2/14.png',
		abv: 4.5,
		ibu: 60,
		ebc: 20,
		category: 'IPA',
		foodPairing: [
			'Spicy chicken skewers',
			'Fish tacos with hot sauce',
			'Lemon pound cake with a ice sugar glaze',
		],
		brewersTips:
			'To intensify hop aromas, try dry hopping with a couple of grams of Amarillo, Citra or Simcoe hops.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
	{
		id: 15,
		name: 'Mixtape 8',
		description:
			'This is a beer that celebrates the land of Oz with big punchy hops that deliver a hefty bitterness which is balanced against the rich, malty backbone.',
		imageUrl: 'https://images.punkapi.com/v2/15.png',
		abv: 7.5,
		ibu: 85,
		ebc: 24,
		category: 'IPA',
		foodPairing: [
			'Spicy and fried foods',
			'Mexican beef mole',
			'Rich chocolate cake with berry coulis',
		],
		brewersTips: 'For the most impact, use the hops as close to the end of the boil as possible.',
		createdAt: new Date(),
		updatedAt: new Date(),
	},
]
